version: '3'

services:
    db:
        build: ./db
        container_name: cdp-mysql
        volumes:
          - db-data:/var/lib/mysql
        network_mode: "host"  
        ports:
          - '3306:3306'
        restart: always
    web:
        build: ./api
        volumes:
          - "./app:/src/app"
        network_mode: "host"  
        ports:
          - "3000:3000"
        container_name: cdp-node
        restart: always

volumes:
    db-data:

